<a href="https://colab.research.google.com/github/jarvis-control/ai_foundation/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install numpy

In [1]:
import numpy as np

# shape - Shows the structure of an array (rows, columns, etc.)
arr = np.array([1, 3, 5, 7])
print('numpy_array:', arr)

arr.shape

numpy_array: [1 3 5 7]


(4,)

In [2]:
# shape - Shows the structure of an array (rows, columns, etc.)
arr2 = np.array([[1, 3, 5, 7], [4, 6, 8, 9]])
print('numpy_arr2:', arr2)

arr2.shape

numpy_arr2: [[1 3 5 7]
 [4 6 8 9]]


(2, 4)

In [3]:
# dtype - Shows the data type stored in the array
a = np.array([1, 2, 3])
print(a.dtype)

int64


In [4]:
# reshape() - Changes the layout/shape of an array without changing its values
a = np.array([1, 2, 3, 4, 5, 6])
b = a.reshape(2, 3)
print('shaped_array:', b)

shaped_array: [[1 2 3]
 [4 5 6]]


In [19]:
# astype() - Converts array values to another data type
a = np.array([1, 2, 3])
b = a.astype(float)
print('float:', b)

float: [1. 2. 3.]


In [6]:
# np.zeros() - Creates an array filled with zeros
# np.ones() - Creates an array filled with ones
# => dummy data
z = np.zeros((2, 3))
o = np.ones((2, 3))

print('zeros:', z)
print('ones:', o)

zeros: [[0. 0. 0.]
 [0. 0. 0.]]
ones: [[1. 1. 1.]
 [1. 1. 1.]]


In [25]:
# ndim - Shows how many dimensions an array has
a = np.array([[1, 2], [3, 4]])
print('ndim:', a.ndim)

ndim: 2


In [8]:
# arange() - Creates a sequence of evenly spaced numbers
a = np.arange(1, 7)
print('arange:', a)

arange: [1 2 3 4 5 6]


In [9]:
# sum() - Adds all values in an array
# mean() - Calculates the average of all values
# max() - Finds the largest value in an array
# min() - Finds the smallest value in an array
a = np.array([1, 2, 3, 4])

print('sum:', a.sum())
print('mean:', a.mean())
print('max:', a.max())
print('min:', a.min())


sum: 10
mean: 2.5
max: 4
min: 1


In [10]:
# flatten() - Converts a multi-dimensional array into a single row of values
a = np.array([[1, 2], [3, 4]])
print('flatten:', a.flatten())

flatten: [1 2 3 4]


In [11]:
# T (transpose) - Swaps rows and columns of an array
a = np.array([[1, 2], [3, 4]])
print('transpose:', a.T)

transpose: [[1 3]
 [2 4]]


In [13]:
# dot() - Performs dot product or matrix multiplication.
# @ - Another operator for matrix multiplication (same purpose as .dot())
a = np.array([[1, 2], [3, 4]])
b = np.array([[2, 0], [1, 2]])
print('dot/multiplication:', a.dot(b))

dot/multiplication: [[ 4  4]
 [10  8]]


In [17]:
# random.rand()
a = np.random.rand(2, 3) # => 0.0 and 1.0 / 0.0 included | 1.0 excluded
print('random_rand:', a)

random_rand: [[0.84473833 0.93169635 0.78586101]
 [0.34409162 0.4461028  0.04081654]]
