<a href="https://colab.research.google.com/github/jarvis-control/ai_foundation/blob/main/students_performance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install pandas numpy

In [2]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("StudentsPerformance.csv.xls")

print("Dataset shape (rows, columns):", df.shape)
print("Column name:", df.columns.tolist())

print("First 5 rows of the dataset:")
print(df.head())

print("Summary statistics:")
print(df.describe())

print("Data types and null info:")
print(df.info())

Dataset shape (rows, columns): (1000, 8)
Column name: ['gender', 'race/ethnicity', 'parental level of education', 'lunch', 'test preparation course', 'math score', 'reading score', 'writing score']
First 5 rows of the dataset:
   gender race/ethnicity parental level of education         lunch  \
0  female        group B           bachelor's degree      standard   
1  female        group C                some college      standard   
2  female        group B             master's degree      standard   
3    male        group A          associate's degree  free/reduced   
4    male        group C                some college      standard   

  test preparation course  math score  reading score  writing score  
0                    none          72             72             74  
1               completed          69             90             88  
2                    none          90             95             93  
3                    none          47             57             44  
4 

In [5]:
print("Average scores by subject.")
df[["math score", "reading score", "writing score"]].mean()

Average scores by subject.


,0
math score,66.089
reading score,69.169
writing score,68.054


In [6]:
print("Maximum scores by subject.")
df[["math score", "reading score", "writing score"]].max()

Maximum scores by subject.


,0
math score,100
reading score,100
writing score,100


In [9]:
print("Minimum scores by subject.")
df[["math score", "reading score", "writing score"]].min()

Minimum scores by subject.


,0
math score,0
reading score,17
writing score,10


In [11]:
print("Correlation:")
df[["math score", "reading score", "writing score"]].corr()

Correlation:


,math score,reading score,writing score
math score,1.000000,0.817580,0.802642
reading score,0.817580,1.000000,0.954598
writing score,0.802642,0.954598,1.000000


In [26]:
df["total score"] = df[["math score", "reading score", "writing score"]].sum(axis=1)
df["average score"] = df["total score"] / 3
df["passed"] = np.where(df["average score"] >= 50, "Yes", "No")

print("New columns preview (total, average, passed):")
print(df[["total score", "average score", "passed"]].head())

New columns preview (total, average, passed):
   total score  average score passed
0          218      72.666667    Yes
1          247      82.333333    Yes
2          278      92.666667    Yes
3          148      49.333333     No
4          229      76.333333    Yes


In [33]:
test_preparation_course = df.groupby('test preparation course')[
    ['math score', 'reading score', 'writing score']
].mean()
print("students score by test preparation course:")
print(test_preparation_course)

print("-----------------------")

# Gender-based average
gender_avg = df.groupby('gender')[
    ['math score', 'reading score', 'writing score']
].mean()
print("Average score by gender:")
print(gender_avg)

print("-----------------------")

# Who passed vs failed
passed_rate = df["passed"].value_counts(normalize=True) * 100
print("Pass rate:\n", passed_rate)

students score by test preparation course:
                         math score  reading score  writing score
test preparation course                                          
completed                 69.695531      73.893855      74.418994
none                      64.077882      66.534268      64.504673
-----------------------
Average score by gender:
        math score  reading score  writing score
gender                                          
female   63.633205      72.608108      72.467181
male     68.728216      65.473029      63.311203
-----------------------
Pass rate:
 passed
Yes    89.7
No     10.3
Name: proportion, dtype: float64


In [34]:
# Convert scores to Numpy array
scores = df[["math score", "reading score", "writing score"]].values

# Mean, Std Deviation
print("Numpy Mean:", np.mean(scores, axis=0))
print("Numpy Std:", np.std(scores, axis=0))

# Z-score (normalize)
z_score = (scores - np.mean(scores, axis=0)) / np.std(scores, axis=0)
print("Z-scores (normalized numbers)")
print(z_score[:5])

# Average 0
# Negative -
# Positive +

Numpy Mean: [66.089 69.169 68.054]
Numpy Std: [15.15549666 14.59289002 15.18805728]
Z-scores (normalized numbers)
[[ 0.39002351  0.19399858  0.39149181]
 [ 0.19207553  1.42747598  1.31326868]
 [ 1.57771141  1.77010859  1.64247471]
 [-1.25954302 -0.83389925 -1.58374436]
 [ 0.65395415  0.60515772  0.45733301]]


In [36]:
# How many students scored above 90 average?
top_scorers = df[df["average score"] >= 90]
print("Top scored students above 90:", len(top_scorers))

# How many failed?
failed = df[df["passed"] == "No"]
print("Failed from exam:", len(failed))

Top scored students above 90: 52
Failed from exam: 103
